NotAnAdminRR: You must be an administrator to access this page.

WelcomeHomepageRR: Welcome to the homepage
SeeArchiveRR: See the archive

NoEntriesRR: There are no entries in the blog
LoginToPostRR: Admins can login to post
NewEntryRR: Post to blog
NewEntryTitleRR: Title
NewEntryContentRR: Content

PleaseCorrectEntryRR: Your submitted entry had some errors, please correct and try again.
EntryCreatedRR title@Text: Your new blog post, #{title}, has been created

EntryTitleRR title@Text: Blog postRR: #{title}
CommentsHeadingRR: Comments
NoCommentsRR: There are no comments
AddCommentHeadingRR: Add a Comment
LoginToCommentRR: You must be logged in to comment
AddCommentButtonRR: Add comment

CommentNameRR: Your display name
CommentTextRR: Comment
CommentAddedRR: Your comment has been added
PleaseCorrectCommentRR: Your submitted comment had some errors, please correct and try again.

HomepageTitleRR: Yesod Blog Demo
BlogArchiveTitleRR: Blog Archive

