name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        args:
        - "--resolver lts-22"
        - "--resolver lts-21"
        - "--resolver lts-20"

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install stack if needed
        shell: bash
        run: |
            set -ex
            if [[ "${{ matrix.os }}" == "macos-latest" ]]
            then
                # macos-latest does not include Haskell tools as of 2024-05-06.
              curl -sSL https://get.haskellstack.org/ | sh
            fi

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack --version
            stack test --fast --no-terminal ${{ matrix.args }}

